AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*

Style/EmptyLines:
  Enabled: false
Style/MethodName:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/Documentation:
  Exclude:
    - app/helpers/**/*
    - app/controllers/**/*
