Style/EmptyLines:
  Enabled: false
Style/MethodName:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
